name: ui
description: UI for ONCO


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  animated_text_kit: ^3.1.0
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  modal_progress_hud: ^0.1.3
  curved_navigation_bar: ^0.3.7
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+21

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf
